- name: DEBIAN | Install dnsmasq
  apt:
    name: dnsmasq
    state: latest
    update_cache: yes
  tags:
    - dnsmasq

# https://serverfault.com/questions/907500/how-to-debug-dnsmasq-requiring-a-service-restart-in-order-to-work
- name: DEBIAN | Change service target to avoid race condition on Pi
  ini_file:
    path: /lib/systemd/system/dnsmasq.service
    section: Unit
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    no_extra_spaces: yes
    mode: '0644'
  when:
    - ansible_facts.service_mgr == 'systemd'
    - ansible_facts.architecture in ['arm', 'aarch64']
  notify: restart dnsmasq
  loop:
    - option: After
      value: network-online.target
    - option: Wants
      value: network-online.target
  tags:
    - dnsmasq

- name: DEBIAN | Stop and disable systmed-resolve
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    daemon_reload: yes
  when: >
    ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version is version('18', '>=')
    or ansible_facts.distribution == 'Debian' and ansible_facts.distribution_major_version is version('12', '>=')
  tags:
    - dnsmasq

- name: DEBIAN | Check /etc/resolv.conf
  stat:
    path: /etc/resolv.conf
  register: resolv_conf
  tags:
    - dnsmasq

- name: DEBIAN | Remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  when: resolv_conf.stat.islnk | bool
  tags:
    - dnsmasq

- name: DEBIAN | Copy /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - dnsmasq
