- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', files) }}"
  vars:
    files:
      - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
      - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
      - "{{ ansible_facts.os_family }}.yml"
      - "{{ ansible_facts.distribution }}.yml"
      - defaults/main.yml
  tags:
    - dnsmasq

- include_tasks: "install-{{ ansible_facts.os_family }}.yml"
  tags:
    - dnsmasq

- name: systemd daemon reload
  systemd:
    daemon_reload: true
  when: ansible_facts.service_mgr == 'systemd'
  tags:
    - dnsmasq

- name: Start and enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true
  register: service_start
  tags:
    - dnsmasq
